### ISSUE TITLE
Incompatibility with Rails 6.0

### ISSUE THREAD

**Issue by NielsKSchjoedt** [newrelic/newrelic-ruby-agent#1338]
When doing

```ruby
class MyClass
  include ::NewRelic::Agent::MethodTracer
  def my_method(limit:)
  end

  add_method_tracer :my_method
end
```

And I call it with rails 6.0.5.1 I get the following error:

```ruby
MyClass.new.my_method(limit: 30)

ArgumentError:
       wrong number of arguments (given 1, expected 0)
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/activesupport-6.0.5.1/lib/active_support/core_ext/numeric/conversions.rb:110:in `to_s'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/activesupport-6.0.5.1/lib/active_support/core_ext/numeric/conversions.rb:110:in `to_s'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/guid_generator.rb:17:in `generate_guid'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/transaction/abstract_segment.rb:34:in `initialize'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/transaction/segment.rb:21:in `initialize'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/tracer.rb:238:in `new'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/tracer.rb:238:in `start_segment'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/method_tracer_helpers.rb:28:in `trace_execution_scoped'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/method_tracer.rb:73:in `trace_execution_scoped'
# /Users/nk/.rvm/gems/ruby-2.7.2@au/gems/newrelic_rpm-8.10.0/lib/new_relic/agent/method_tracer.rb:331:in `block (2 levels) in _nr_define_traced_method'
# ./my_class.rb:3:in `my_method'
```

The method it traces back to is this one: https://github.com/rails/rails/blob/v6.0.5.1/activesupport/lib/active_support/core_ext/numeric/conversions.rb

**Comment by NielsKSchjoedt** [comment]
BTW: I did a `binding.pry` on line `/Users/nk/.rvm/gems/ruby-2.7.2@au/gems/activesupport-6.0.5.1/lib/active_support/core_ext/numeric/conversions.rb:110` to inspect the context. `self.class` return `Float`

**Comment by NielsKSchjoedt** [comment]
I found the issue. I had a spec that stubbed `rand` 🙈 `allow_any_instance_of(Object).to receive(:rand).and_return(1.0)`

**Comment by fallwith** [comment]
Hi @NielsKSchjoedt, we're very glad you were able to track down the cause of this one.
