### ISSUE TITLE
CI: Address compatibility with Active Record 7.0.5

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2038]
The recently released Active Record v7.0.5 works great from an agent instrumentation perspective and even passes all CI checks locally. But for some reason with GHA, we encounter the following new error:

```shell
/opt/hostedtoolcache/Ruby/3.3.0-preview1/x64/lib/ruby/gems/3.3.0+0/gems/activerecord-7.0.5/lib/active_record/tasks/database_tasks.rb:73:in `check_protected_environments!': You are attempting to modify a database that was last run in `test` environment. (ActiveRecord::EnvironmentMismatchError)
You are running in `default_env` environment. If you are sure you want to continue, first set the environment using:

        bin/rails db:environment:set


	from /opt/hostedtoolcache/Ruby/3.3.0-preview1/x64/lib/ruby/gems/3.3.0+0/gems/activerecord-7.0.5/lib/active_record/railties/databases.rake:18:in `block (2 levels) in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.0-preview1/x64/lib/ruby/gems/3.3.0+0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
```

**Comment by fallwith** [comment]
resolved with #2039
