### ISSUE TITLE
Does newrelic rpm support elasticsearch 5?

### ISSUE THREAD

**Issue by hothero** [newrelic/newrelic-ruby-agent#2328]
## Description
I couldn't enable newrelic rpm since it will break my elasticsearch functions. This is the log

``` 
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/tracer.rb:22:in `state'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/tracer.rb:32:in `tracing_enabled?'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:14:in `perform_request_with_tracing'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:41:in `block in perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:34:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:44:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:40:in `perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `block in perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:14:in `perform_request_with_tracing'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:41:in `block in perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:34:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:44:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:40:in `perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `block in perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:14:in `perform_request_with_tracing'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:41:in `block in perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:34:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/tracer.rb:44:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/elasticsearch.rb:40:in `perform_request_with_scout_instruments'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `block in perform_request'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/instrumentation.rb:14:in `perform_request_with_tracing'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/elasticsearch/prepend.rb:10:in `perform_request'
<truncated 9014 additional frames>
/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/middleware/ssl.rb:77:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/lib/middleware/queue_time/middleware.rb:21:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/hirefire-resource-0.10.1/lib/hirefire/middleware.rb:37:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/rack-cors-2.0.1/lib/rack/cors.rb:102:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/middleware_summary.rb:58:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:530:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/hirefire-resource-0.10.1/lib/hirefire/middleware.rb:37:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/configuration.rb:272:in `call'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:100:in `block in handle_request'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/request.rb:99:in `handle_request'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:443:in `process_client'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/server.rb:241:in `block in run'
/app/vendor/bundle/ruby/3.2.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/tracer.rb:433:in `block (2 levels) in thread_block_with_current_transaction'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/app/vendor/bundle/ruby/3.2.0/gems/newrelic_rpm-9.6.0/lib/new_relic/agent/tracer.rb:432:in `block in thread_block_with_current_transaction'
``` 

does that mean the newrelic conflict with scout_rpm? I tried one removing scout_rpm as well but it didn't help if I remember correctly.
Or does newrelic rpm not support elasticsearch 5?

## Expected Behavior
it should not cause errors

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by hannahramadan** [comment]
Hi @hothero 👋 While we don't officially support Elasticsearch 5, our instrumentation shouldn't be causing errors. There may be a conflict with the way both New Relic and Scout are attempting to instrument the Elasticsearch library.

In your `newrelic.yml` file, can you see if adding the following configuration setting helps?

```ruby
instrumentation.elasticsearch: chain
```
If the above change doesn't resolve the error, can you provide a stack trace that includes the error that is being raised?
