### ISSUE TITLE
Getting "actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'" on rails app

### ISSUE THREAD

**Issue by thestelz** [newrelic/newrelic-ruby-agent#2433]
## Description

I have noticed since I have updated our app to `9.7.1` that there are a bunch of errors:

<details>
<summary>Stack Trace</summary>

```stacktrace
actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'railties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'activesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'railties (5.2.6) lib/rails/rack/logger.rb:26:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'rack (2.2.3) lib/rack/method_override.rb:24:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'rack (2.2.3) lib/rack/runtime.rb:22:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'rack (2.2.3) lib/rack/sendfile.rb:110:in `call'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'railties (5.2.6) lib/rails/engine.rb:524:in `call'railties (5.2.6) lib/rails/railtie.rb:190:in `public_send'railties (5.2.6) lib/rails/railtie.rb:190:in `method_missing'newrelic_rpm (9.7.1) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'unicorn (5.4.1) lib/unicorn/http_server.rb:606:in `process_client'unicorn (5.4.1) lib/unicorn/http_server.rb:701:in `worker_loop'unicorn (5.4.1) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'unicorn (5.4.1) lib/unicorn/http_server.rb:142:in `start'unicorn (5.4.1) bin/unicorn_rails:209:in `<top (required)>'/home/ubuntu/.rvm/gems/ruby-2.5.3/bin/unicorn_rails:23:in `load'/home/ubuntu/.rvm/gems/ruby-2.5.3/bin/unicorn_rails:23:in `<main>'
```

</details>

## Expected Behavior

To not see these errors 

## Steps to Reproduce

Not 100% sure what the root cause is or if it could be on our end. I have updated an old app to the latest version (`9.7.1`) from `5.7.0.350`

## Your Environment

Ruby: `2.5.3`
Rails: `5.26`
NR: `9.7.1`
Unicorn: `5.4.1`
Ubuntu: `20.04.3 LTS` (`GNU/Linux 5.15.0-1051-aws x86_64`)

## Additional context

I have attached a scrubbed json file as the output from `nrdiag` and a text file with a sample of the `newrelic.log` on the server.

Not sure when I started receiving these error nor if they are due to a config setup that I have or if there is actually a bug somewhere. Unfortunately, I can't provide a test app at this time due to time limitations.

Sorry if this is the wrong place to go, but I'm just not sure what could be causing this issue, so I figured I'd go to people smarter than me.

[NRGHI.zip](https://github.com/newrelic/newrelic-ruby-agent/files/14224765/NRGHI.zip)

**Comment by kaylareopelle** [comment]
Hi @thestelz, thanks for reaching out to us with this detailed report! This is a great place to come for any bug reports or feature requests related to the agent. I appreciate your patience while we reviewed your report.

I have a few questions for you to help us with debugging:
#### 1. What's going on in your application when these errors start?

Do these errors happen on startup, or at a different time?

#### 2. What's the earliest agent version where this error starts to occur?

Did you migrate directly from version 5.7.0 to 9.7.1 or did you stop at each major version along the way?

We recommend updating the agent one major version at a time using our migration guides to make changes to your API calls and your configuration along the way. We don't have a migration guide for the move from 5.x to 6.x, but we have them for the following versions:
* [Ruby agent 6.x to 7.x migration guide](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-7x-guide/)
* [Ruby agent 7.x to 8.x migration guide](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-8x-guide/)
* [Ruby agent 8.x to 9.x migration guide](https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/migration-9x-guide/)

If you moved directly to version 9.7.1, I recommend winding back your application to 5.7.0 and updating the agent one major version at a time to see where the error starts, and then narrow it down to the minor version.

If you know precisely what version the error started in, we can start to dive into the code from that version to try to create a reproduction.

#### 3. Does toggling the following configuration options make the error go away?
* [`disable_middleware_instrumentation`](https://docs.newrelic.com/docs/apm/agents/ruby-agent/configuration/ruby-agent-configuration/#disable_middleware_instrumentation): `true`. This will cause the agent to skip instrumenting middlewares, which should include `DebugExceptions`. However, this turns off instrumentation for all middlewares, so you'll likely see considerably fewer segments in your transactions. 
* [`disable_action_dispatch`](https://github.com/newrelic/newrelic-ruby-agent/blob/c372d90848f50c74a845eedc120bda8af96af8a1/lib/new_relic/agent/configuration/default_source.rb#L1128): `false`. This will allow the agent to instrument ActionDispatch through monkey patching instead of ActiveSupport::Notifications, which is the default method for Rails 6+.

I'd love to know if adjusting either of these configurations makes a difference.

**Comment by thestelz** [comment]
Hi @kaylareopelle, thanks for getting back to me.

> #### 1. What's going on in your application when these errors start?

That's what I'm not sure about, but my best guess is DelayedJobs might be triggering these due to the timing and finding this in the log file:

>NewRelic::Agent::Samplers::DelayedJobSampler not available: No DJ worker present. Skipping DJ queue sampler

> Do these errors happen on startup, or at a different time?

No, it appears this is happening at indeterminate intervals, not during a start up of the app or when an update has been released.

> #### 2. What's the earliest agent version where this error starts to occur?

That is one of the issues. We weren't aware of this log file until recently (it is stored directly on the server and not sent to NR), so I'm not sure when the errors started to show up as they are rotated and deleted.

> Did you migrate directly from version 5.7.0 to 9.7.1 or did you stop at each major version along the way?

We released them by minor versions each time to make sure everything was working as expected. I did read over the migration guides on every major update. I even ran the scripts to rewrite the `newrelic.yml` on each major update (I then updated the config to fit our needs).

> #### 3. Does toggling the following configuration options make the error go away?

I will let you know as we only do releases at set times (to make sure they are outside of peak times) and days due to our busiest days (mgmt doesn't want any issues introduced on those days, just in case). This means those updates might not happen until next week.

-----

DelayedJob: `4.1.9`

-----

I'm reading over the log file again and maybe it isn't that big of a deal as there aren't any errors listed nor any issues with anything I know of, so maybe this has always been there, but now we have just noticed it.

Does NR create a debug log directly on the server (`newrelic_agent.log`)?

**Comment by kaylareopelle** [comment]
Hi @thestelz

Thanks for your response! Your answers are really helpful. 

> That's what I'm not sure about, but my best guess is DelayedJobs might be triggering these due to the timing and finding this in the log file:
> > NewRelic::Agent::Samplers::DelayedJobSampler not available: No DJ worker present. Skipping DJ queue sampler

To test this theory, you could try updating your configuration to set `disable_delayed_job_sampler: false`. I forgot to mention this earlier, but we recommend you change only one configuration option at a time during this debugging process to help us narrow down the root cause.

> That is one of the issues. We weren't aware of this log file until recently

Can you give us some details about the source of this log file? Was it in one of the `newrelic_*` log files?

> We released them by minor versions each time to make sure everything was working as expected...

It's great to hear that you followed that thorough updating process! I'm sorry an error came up despite your diligence.

> I will let you know as we only do releases at set times 

No problem. Thanks for the context. We'll keep an eye out for your response. 

> I'm reading over the log file again and maybe it isn't that big of a deal as there aren't any errors listed nor any issues with anything I know of, so maybe this has always been there, but now we have just noticed it.

What happens in your application when this error is raised? Does this cause your application to crash? Does it safely recover?

> Does NR create a debug log directly on the server (newrelic_agent.log)?

New Relic creates a log in a `log` directory at the root of your application. You can increase the verbosity of the log using the `log_level` configuration. It might be helpful to collect debug-level logs from your application while the error occurs, but GitHub is often not the best place to share those logs. 

If you would like to go that route, depending on your support level you can either engage the [New Relic Support Community](https://discuss.newrelic.com/) or open a [support ticket](https://support.newrelic.com/new-ticket). If you open a ticket using either of these forums, please include a link to this GitHub issue in your description. Alternately, we can keep the conversation here, but it might be a lot of effort to effectively scrub the logs.

**Comment by thestelz** [comment]
@kaylareopelle I have released the following change on 2/20 and let it run for 24 hours.

```diff
-disable_delayed_job_sampler: false
+disable_delayed_job_sampler: true
```

It has resolved the 

>NewRelic::Agent::Samplers::DelayedJobSampler not available: No DJ worker present. Skipping DJ queue sampler

issue via the logs.

> Can you give us some details about the source of this log file? Was it in one of the `newrelic_*` log files?

I was dumb on this one and missed the

```yaml
# Logging level for log/newrelic_agent.log; options are error, warn, info, or
# debug.
log_level: info
```

in our config file. This is why that log is created.

> What happens in your application when this error is raised? Does this cause your application to crash? Does it safely recover?

No crashes. It does safely recover.

----

Having said all of that, we are still getting the `actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:65:in 'call'` error, but it appears to happen when we get a request to a route that doesn't exist.

Not sure if this expected behavior or not, but since it is only showing in our logs without any errors in our application I think they can be ignored.

Let me know if you would like to investigate this further.

Thanks for you help!
