### ISSUE TITLE
Dependency detection: duplicated log entries, potentially duplicated invocations

### ISSUE THREAD

**Issue by fallwith** [newrelic/newrelic-ruby-agent#2516]
**Issues:**
- dependency detection logic is double reported for every instrumented gem
- dependency detection logic may possibly also be involving doubled, redundant invocations

**To reproduce:**
- set the log level to debug and init the agent
- observe the log to see duplicated detection lines such as these:

```
DEBUG : Using auto configuration value for bunny to configure instrumentation
DEBUG : Using auto configuration value for bunny to configure instrumentation
DEBUG : Using auto configuration value for concurrent_ruby to configure instrumentation
DEBUG : Using auto configuration value for concurrent_ruby to configure instrumentation
DEBUG : Using auto configuration value for curb to configure instrumentation
DEBUG : Using auto configuration value for curb to configure instrumentation
DEBUG : Using auto configuration value for delayed_job to configure instrumentation
DEBUG : Using auto configuration value for delayed_job to configure instrumentation
```

**Source:**
The log output is generated by the `fetch_config_value` method defined in `lib/new_relic/dependency_detection.rb`.

**Pathways:**
The doubled log output is produced by 2 different call stacks:

``` 
# pathway 1
"lib/new_relic/dependency_detection.rb:183:in `fetch_config_value'",
"lib/new_relic/dependency_detection.rb:202:in `config_value'",
"lib/new_relic/dependency_detection.rb:170:in `block (2 levels) in <class:Dependent>'",
"lib/new_relic/dependency_detection.rb:139:in `allowed_by_config?'",
"lib/new_relic/dependency_detection.rb:122:in `check_dependencies'",
"lib/new_relic/dependency_detection.rb:64:in `dependencies_satisfied?'",
"lib/new_relic/dependency_detection.rb:28:in `block in detect!'",
"lib/new_relic/dependency_detection.rb:27:in `each'",
"lib/new_relic/dependency_detection.rb:27:in `detect!'",
"lib/new_relic/control/instrumentation.rb:64:in `_install_instrumentation'",
"lib/new_relic/control/instrumentation.rb:47:in `install_instrumentation'",
"lib/new_relic/control/private_instance_methods.rb:39:in `init_instrumentation'",
"lib/new_relic/control/instance_methods.rb:75:in `init_plugin'",

# pathway 2
"lib/new_relic/dependency_detection.rb:183:in `fetch_config_value'",
"lib/new_relic/dependency_detection.rb:202:in `config_value'",
"lib/new_relic/dependency_detection.rb:170:in `block (2 levels) in <class:Dependent>'",
"lib/new_relic/dependency_detection.rb:31:in `block in detect!'",
"lib/new_relic/dependency_detection.rb:27:in `each'",
"lib/new_relic/dependency_detection.rb:27:in `detect!'",
"lib/new_relic/control/instrumentation.rb:64:in `_install_instrumentation'",
"lib/new_relic/control/instrumentation.rb:47:in `install_instrumentation'",
"lib/new_relic/control/private_instance_methods.rb:39:in `init_instrumentation'",
"lib/new_relic/control/instance_methods.rb:75:in `init_plugin'",
```

**Impact:**
- The agent logs more than it should when using a debug log level (default = info)
- The agent potentially does more detection work that it needs to at startup

**Comment by kaylareopelle** [comment]
This one reminds me of #2434

**Comment by kaylareopelle** [comment]
I love the detailed repro and data in your description here

**Comment by fallwith** [comment]
Let's confirm the output shown in the description has gone away once #2434 has been completed.

**Comment by fallwith** [comment]
We'll let #2434 drive this one. Closing as a dupe.

**Comment by hannahramadan** [comment]
This issue turns out not to be a dupe of #2434. There is some additional work that this ticket mentions, but that should be further investigated. On startup, the agent logs multiple DEBUG messages. For example in one test with `instrumentation.view_component` set to `chain`, we get 6 logs:

```
DEBUG : Using chain configuration value for view_component to configure instrumentation
DEBUG : Using chain configuration value for view_component to configure instrumentation
DEBUG : Using auto configuration value for view_component to configure instrumentation
DEBUG : Using auto configuration value for view_component to configure instrumentation
DEBUG : Using auto configuration value for view_component to configure instrumentation
DEBUG : Using auto configuration value for view_component to configure instrumentation
```
