### ISSUE TITLE
to_app instrumentation conflicting with sqreen gem

### ISSUE THREAD

**Issue by lloeki** [newrelic/newrelic-ruby-agent#461]
## Description

NewRelic instrumentation is using alias method chaining on Rack's `to_app`, which conflicts with other instrumentors using `Module#prepend`.

See [this NewRelic article](https://blog.newrelic.com/engineering/ruby-agent-module-prepend-alias-method-chains/)

This causes an infinite call loop when used with the `sqreen` gem, where:

- `sqreen < 1.21.0` did not use `Module#prepend` by default
- `sqreen >= 1.21.0` uses `Module#prepend` by default

## Expected Behavior

Don't produce an infinite call loop ;)

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

![image](https://user-images.githubusercontent.com/75445/94697040-014ff000-0338-11eb-9540-2114a4d8d895.png)

## Steps to Reproduce

- use both newrelic_rpm 6.13.0 and sqreen 1.21.0 gems
- boot Rails application

**Comment by mwlang** [comment]
@lloeki Thank you for submitting this issue.  We agree that we need to move more of our instrumentations to using `prepend` approach for instrumenting.  `Rack` is a core instrumentation within the Agent, so we'll want to be especially careful about changing its implementation.

I'm going to put a `help wanted` and `good first issue` on this one for now.  We'll evaluate periodically to prioritize for inclusion in the feature roadmap and/or for one of our upcoming bug smash sprints.

In the meantime, you can work around this with a variation on what our blog article proposed:

In your Gemfile, include `sqreen` with the `require: false` option.

```yaml
gem 'newrelic_rpm'
gem 'sqreen', require: false
```
Then in your `config/application.rb` or one of your environments file as appropriate, take advantage of the Rails engine initializer to load `sqreen` after all other gems initialize (including the Ruby Agent) and just before the Middleware stack gets frozen with this technique:

```ruby
module DemoApp
  class Application < Rails::Application
    # other settings redacted for brevity...
    initializer :sqreen do |app|
      require 'sqreen'
    end    
  end
end
```

**Comment by lloeki** [comment]
We have just released a workaround specific to NewRelic, effective starting with `sqreen` gem v1.21.1, obviating the need for the above workaround for a better experience for both Sqreen and NewRelic users.

**Comment by single-stop-tony** [comment]
@lloeki The issue appears to be happening again with after updating to NewRelic 6.14.0

```bash
#<Thread:0x00007f9a0bf2d828 /usr/local/rvm/gems/ruby-2.7.2/gems/sqreen-1.22.0/lib/sqreen/endpoint_testing.rb:57 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9360: from /usr/local/rvm/gems/ruby-2.7.2/gems/sqreen-1.22.0/lib/sqreen/endpoint_testing.rb:58:in `block in test_endpoints'
	9359: from /usr/local/rvm/gems/ruby-2.7.2/gems/sqreen-1.22.0/lib/sqreen/endpoint_testing.rb:90:in `thread_main'
	9358: from /usr/local/rvm/gems/ruby-2.7.2/gems/sqreen-1.22.0/lib/sqreen/endpoint_testing.rb:110:in `test_with_store_variants'
	9357: from /usr/local/rvm/gems/ruby-2.7.2/gems/sqreen-1.22.0/lib/sqreen/endpoint_testing.rb:140:in `do_test'
	9356: from /usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:1241:in `get'
	9355: from /usr/local/rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:55:in `request'
	9354: from /usr/local/rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.14.0/lib/new_relic/agent.rb:506:in `disable_all_tracing'
	9353: from /usr/local/rvm/gems/ruby-2.7.2/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:56:in `block in request'
	 ... 9348 levels...
	   4: from /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
	   3: from /usr/local/rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
	   2: from /usr/local/rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
	   1: from /usr/local/rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:215:in `unicode_compose_pair'
/usr/local/rvm/gems/ruby-2.7.2/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:305:in `lookup_unicode_composition': stack level too deep (SystemStackError)
```

**Comment by lloeki** [comment]
@single-stop-tony I'm taking note of it.

To ensure the best compatibility possible for our customers, our instrumentation system is configurable and can do either alias method chain or module prepend, both at the global level and exceptionally at the local level for specific methods.

To combat the `to_app` problem in this issue, in sqreen 1.21.1, we have introduced this local strategy in our code:

```
      def to_app_hook_strategy
        if Sqreen::Dependency::NewRelic.bundled? || Sqreen::Dependency::NewRelic.required?
          :chain
        else
          :prepend
        end
      end
```

To improve compatibility with other APMs, including Skylight, we have introduced such global strategies in 1.22.0:

```
    if Gem::Specification.select { |s| s.name == 'skylight' && Gem::Requirement.new('< 5.0.0.beta').satisfied_by?(Gem::Version.new(s.version)) }.any?
      Sqreen::Weave.logger.debug { "strategy: :prepend unavailable with skylight < 5.0.0.beta, switching to :chain" }
      strategy_hints << [:chain, 'skylight', '< 5.0.0.beta']
    end
    if Gem::Specification.select { |s| s.name == 'skylight' && Gem::Requirement.new('>= 5.0.0.beta').satisfied_by?(Gem::Version.new(s.version)) }.any?
      Sqreen::Weave.logger.debug { "strategy: :chain unavailable with skylight >= 5.0.0.beta, switching to :prepend" }
      strategy_hints << [:prepend, 'skylight', '>= 5.0.0.beta']
    end
```

I see in your bundle that you're using skylight 4.3.1 and newrelic_rpm 6.13 as currently deployed. I don't know if something changed on the NR side of things between 6.13 and 6.14, but what I know for sure is that skylight 4.3.1 makes sqreen 1.22.0 use alias method chain globally to not break skylight. If indeed NewRelic moved from prepend in 6.14 for that specific hook point (or more), then I would advise to [update to skylight 5.0](https://github.com/skylightio/skylight-ruby/issues/155#issuecomment-722588811), which also uses module prepend throughout. This will relax sqreen's auto detection which should help for that specific issue you encounter.

But, when looking at the big picture, the whole situation is a case of breaking the Nash equilibrium: if NewRelic hasn't updated all of its hook points to module prepend, then it's bound to blow up when someone else hooks at the same place with the incompatible method. Case in point, as soon as NR moves `to_app` to prepend, sqreen's above contingency will fail since I can't code newrelic_rpm's version in anticipation because I don't know the version in which they'll fix it.

As I detailed [over here to the Elastic APM team](https://github.com/elastic/apm-agent-ruby/issues/379#issuecomment-717341248) (and [not alone in doing so](https://github.com/airbrake/airbrake/issues/1080#issuecomment-609569006)), the only winning move is for all of us to drop alias method chain.

**Comment by single-stop-tony** [comment]
@lloeki updating to skylight 5.0.0.beta.3 does appear to fix the issue for me - thanks!

**Comment by lloeki** [comment]
> I'm going to put a help wanted and good first issue on this one for now. We'll evaluate periodically to prioritize for inclusion in the feature roadmap and/or for one of our upcoming bug smash sprints.

@mwlang This issue has been automatically closed, but shouldn't that issue be kept open for that roadmaping to happen?

I noticed that `newrelic_rpm` 6.14 has seen [some movement](https://github.com/newrelic/newrelic-ruby-agent/commit/cde7d105cb669f6a9b2afa93076c9b1dd88b1bd5#diff-0d7d26972d28b50653a503173e4db2268652c26218ceef1279fe6970ec144fea) to prepend (at least on `Net::HTTP`).

FYI here's the current status of things using prepend:

- `opentelemetry` since the beginning
- `scout_apm` >= 2.5.2
- `ddtrace` >= 0.27
- `skylight` >= 5.0.0.beta
- `elastic-apm` >= 4.0 (merged, release upcoming)
- `airbrake` >= 11.0.2
- and so, `newrelic_rpm` >= 6.14 (partially: Rack's to_app is still alias method chain'ed, and [ActiveRecord](https://github.com/newrelic/newrelic-ruby-agent/blob/c9203be16af3468f275bbde078dc2805ad878655/lib/new_relic/agent/instrumentation/active_record.rb#L23) is behind `prepend_active_record_instrumentation` that apparently [defaults](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration) to `false`).
