### ISSUE TITLE
cannot modify frozen hash with noticed_errors

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#535]
## Description
```ruby
ruby test/new_relic/agent/transaction/segment_test.rb
```
leads to:
```
..........E............

Finished in 2.949703s, 7.7974 runs/s, 17.6289 assertions/s.

  1) Error:
NewRelic::Agent::Transaction::SegmentTest#test_nested_segment_has_error_attributes_after_error:
FrozenError: can't modify frozen Hash
    /Users/mlang/projects/agents/ruby/agent/github/lib/new_relic/noticed_error.rb:142:in `merge!'
    /Users/mlang/projects/agents/ruby/agent/github/lib/new_relic/noticed_error.rb:142:in `build_error_attributes'
    /Users/mlang/projects/agents/ruby/agent/github/test/agent_helper.rb:421:in `build_deferred_error_attributes'
    test/new_relic/agent/transaction/segment_test.rb:357:in `rescue in capture_nested_segment_with_error'
    test/new_relic/agent/transaction/segment_test.rb:345:in `capture_nested_segment_with_error'
    test/new_relic/agent/transaction/segment_test.rb:69:in `test_nested_segment_has_error_attributes_after_error'
```

On the current `dev` branch.  This is a regression bug that somehow got through our CI.

## Additional context

Initially thought this was.a new Ruby 3.0.0 issue, but it also occurs on Rubies 2.5, 2.6. and 2.7.

**Comment by mwlang** [comment]
Turns out the bug is only manifesting in the test suite and not in the Agent's runtime code.
