### ISSUE TITLE
Tracer start_transaction_or_segment undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by warp** [newrelic/newrelic-ruby-agent#545]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
When middleware tracing attempts to start a new segment it can fail due to nesting_max_depth indicating that a segment has already been created but the segments array is empty.

## Expected Behavior
This should not result in an exception.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
```
Exception during Tracer.start_transaction_or_segment 
undefined method `name' for nil:NilClass 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/transaction.rb:475:in `nest_initial_segment' 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/transaction.rb:467:in `create_nested_segment' 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/tracer.rb:153:in `start_transaction_or_segment' 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:93:in `call' 
/app/lib/middleware/request_context.rb:24:in `call' 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call' 
/app/vendor/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call' 
/app/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-6.13.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/configuration.rb:238:in `call' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/server.rb:638:in `block in handle_request' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/thread_pool.rb:337:in `with_force_shutdown' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/server.rb:637:in `handle_request' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/server.rb:394:in `process_client' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/server.rb:250:in `block in run' 
/app/vendor/bundle/ruby/2.7.0/gems/puma-5.0.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread' 
```

## Steps to Reproduce
This issue happens very infrequently but is possibly caused by a thread race condition where a different transaction is resolved.

**Comment by olleolleolle** [comment]
Thanks, @warp! I was following up on this, and found your fix! :hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:

**Comment by tannalynn** [comment]
7.0.0 has been released! This fix for this issue was included in this release.
