### ISSUE TITLE
Middlewares sometimes loaded multiple times in jRuby and Sinatra

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#563]
## Description

Unfortunately we see that the "Bugfix: Gracefully handles NilClass as a Middleware Class when instrumenting" you did in the Ruby agent did not fix our issues and we're having the same problems on service startup.

Sometimes we run into a "NoMethodError: undefined method `[]' for nil:NilClass" error on startup of our services. The stacktrace looks as follows:

```
undefined method `[]' for nil:NilClass
…service/vendor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/sinatra.rb:105:in `block in try_to_use'
org/jruby/RubyArray.java:4493:in `any?'
…service/vendor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/sinatra.rb:105:in `try_to_use'
…service/vendor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/sinatra.rb:98:in `block in build_with_newrelic'
org/jruby/RubyArray.java:1809:in `each'
…service/vendor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/sinatra.rb:97:in `build_with_newrelic'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1528:in `new'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1517:in `prototype'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
…dor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
org/jruby/RubyArray.java:1809:in `each'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
…dor/bundle/jruby/2.5.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/configuration.rb:246:in `call'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/request.rb:76:in `block in handle_request'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/request.rb:75:in `handle_request'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/server.rb:431:in `process_client'
/opt/app-root/service/vendor/bundle/jruby/2.5.0/gems/puma-5.1.1-java/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

This `try_to_use` function, which throws the error iterates of the middlewares but one of them is nil, which leads to the crash. I added some logging to have a look how those middlewares look like while the crash is occuring an this is the content of the `app.middleware` variable at the crash:

```
[
  [ErrorHandler::Middleware, [{:logger=>#<RtLogger::Logger:0x5f25f80>, :response_handler=>ResponseHandler::Error}], nil], 
  [NewRelicWrapper::Middleware, [], nil], 
  [Identities::Middleware, [], nil], 
  nil, 
  [NewRelic::Rack::BrowserMonitoring, [], nil], 
  [NewRelic::Rack::BrowserMonitoring, [], nil], 
  [NewRelic::Rack::BrowserMonitoring, [], nil], 
  [NewRelic::Rack::BrowserMonitoring, [], nil]
]
```

Normally, when the app starts successfully, the app.middleware variable looks as follows:

```
[
  [ErrorHandler::Middleware, [{:logger=>#<RtLogger::Logger:0x00005609>, :response_handler=>ResponseHandler::Error}], nil], 
  [NewRelicWrapper::Middleware, [], nil], 
  [Identities::Middleware, [], nil], 
  [NewRelic::Rack::BrowserMonitoring, [], nil]
]
```

## Expected Behavior
No nil middleware and only one BrowserMonitoring middleware.

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

**Comment by mwlang** [comment]
Moved this back to the 7.0 target because the work is done and we have a pending PR in the wings for it.
