### ISSUE TITLE
Segfault when using with Rack::RubyProf

### ISSUE THREAD

**Issue by chaffeqa** [newrelic/newrelic-ruby-agent#700]
## Description
When attempting to make any Rails request with `Rack::RubyProf` and new_relic gem (using an env that doesnt exist in the `new_relic.yml` you get a segmentation fault when the request finishes.  Removing the new_relic gem or setting `monitor_mode: false` for that env leads to no longer segfaulting

## Your Environment
```
rails (5.2.5)
ruby-prof (1.4.3)
newrelic_rpm (6.15.0)
```

**Comment by wyhaines** [comment]
Since this is marked community, I'll take a look at it.  :)

@chaffeqa, would it be possible for you to give me a little more information?

Specifically, when there is a segmentation fault, there is some output that Ruby dumps with that. Could you recreate the issue, and paste that output into the ticket?

Also, can you clarify something for me? Your issue description says this:

> using an env that doesnt exist in the new_relic.yml

Does that mean that the segmentation fault only occurs when using Rack::RubyProf along with an env that doesn't exist in the new_relic.yml, but that if the env does exist in the new_relic.yml, there is no segmentation fault?

i.e. since it doesn't exist in the new_relic.yml, you are using environment variables to provide all of your configuration?

What application server are you using? Puma? Are you running it multithreaded?

Thank you in advance for answers to these questions. If you can fill in some of the gaps here, I can probably sort out what is going wrong.

**Comment by angelatan2** [comment]
@chaffeqa Did you get a chance to review @wyhaines comments?  It would help us if we can see the error log or seg fault dumps.  

We would appreciate it if you can help us with the answers to the above questions on configuration, type of server and if you are running the server multithreaded.  

Thanks again.  Please note that without these answers, it will be difficult for us to make progress on this issue.

**Comment by chaffeqa** [comment]
Sorry been a busy season for our company :( 

here is an example of a segfault:

```
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/thread.rb:5: [BUG] Segmentation fault at 0x0000000000000020
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin19]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0085 p:---- s:0700 e:000699 CFUNC  :call_tree
c:0084 p:0004 s:0696 e:000695 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/thread.rb:5
c:0083 p:0077 s:0692 e:000689 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_p
c:0082 p:0006 s:0685 e:000684 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_p
c:0081 p:0007 s:0680 e:000679 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_p [FINISH]
c:0080 p:---- s:0676 e:000675 CFUNC  :each
c:0079 p:0010 s:0672 e:000671 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_p
c:0078 p:0029 s:0668 e:000667 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_p
c:0077 p:0011 s:0662 e:000661 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:89 [FINISH]
c:0076 p:---- s:0658 e:000657 CFUNC  :open
c:0075 p:0208 s:0652 e:000651 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:88 [FINISH]
c:0074 p:---- s:0645 e:000644 CFUNC  :each
c:0073 p:0007 s:0641 e:000640 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:75
c:0072 p:0082 s:0635 e:000634 METHOD /app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:36
c:0071 p:0102 s:0626 e:000625 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0070 p:0036 s:0615 e:000614 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/tempfile_reaper.rb:15
c:0069 p:0102 s:0606 e:000605 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0068 p:0008 s:0595 e:000594 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/etag.rb:25
c:0067 p:0102 s:0584 e:000583 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0066 p:0049 s:0573 e:000572 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/conditional_get.rb:25
c:0065 p:0102 s:0564 e:000563 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0064 p:0008 s:0553 e:000552 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/head.rb:12
c:0063 p:0102 s:0545 e:000544 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0062 p:0024 s:0534 e:000533 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/http/content
c:0061 p:0102 s:0522 e:000521 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0060 p:0030 s:0511 e:000510 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:259
c:0059 p:0006 s:0500 e:000499 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:253
c:0058 p:0102 s:0495 e:000494 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0057 p:0024 s:0484 e:000483 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/c
c:0056 p:0102 s:0474 e:000473 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0055 p:0009 s:0463 e:000462 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/c
c:0054 p:0029 s:0460 e:000459 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.
c:0053 p:0010 s:0451 e:000450 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/c
c:0052 p:0102 s:0444 e:000443 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0051 p:0030 s:0433 e:000432 METHOD /app/lib/rails/extensions/middleware.rb:213
c:0050 p:0102 s:0428 e:000427 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0049 p:0024 s:0417 e:000416 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/d
c:0048 p:0102 s:0406 e:000405 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0047 p:0024 s:0395 e:000394 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/s
c:0046 p:0102 s:0388 e:000387 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0045 p:0042 s:0377 e:000376 METHOD /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:38
c:0044 p:0009 s:0367 e:000366 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:26
c:0043 p:0004 s:0364 e:000363 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0042 p:0013 s:0361 e:000360 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0041 p:0012 s:0355 e:000354 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0040 p:0041 s:0350 e:000349 METHOD /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:26
c:0039 p:0102 s:0344 e:000343 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0038 p:0010 s:0333 e:000332 BLOCK  /app/lib/rails/extensions/middleware.rb:184
c:0037 p:0045 s:0330 e:000329 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/core_ext/t
c:0036 p:0133 s:0323 e:000322 BLOCK  /app/lib/rails/extensions/middleware.rb:183
c:0035 p:0004 s:0319 e:000318 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0034 p:0013 s:0316 e:000315 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0033 p:0012 s:0310 e:000309 METHOD /app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_log
c:0032 p:0179 s:0305 E:002218 METHOD /app/lib/rails/extensions/middleware.rb:173
c:0031 p:0102 s:0296 e:000295 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0030 p:0059 s:0285 e:000284 METHOD /app/lib/rails/extensions/middleware.rb:14
c:0029 p:0102 s:0280 e:000279 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0028 p:0008 s:0269 e:000268 METHOD /app/lib/rails/extensions/middleware.rb:198
c:0027 p:0102 s:0263 e:000262 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0026 p:0036 s:0252 e:000251 METHOD /app/lib/rails/extensions/middleware.rb:235
c:0025 p:0102 s:0247 e:000246 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0024 p:0049 s:0236 e:000235 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/lock.rb:17
c:0023 p:0102 s:0229 e:000228 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0022 p:0053 s:0218 e:000217 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/r
c:0021 p:0102 s:0212 e:000211 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0020 p:0039 s:0201 e:000200 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/r
c:0019 p:0102 s:0195 e:000194 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0018 p:0091 s:0184 e:000183 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/method_override.rb:22
c:0017 p:0102 s:0178 e:000177 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0016 p:0020 s:0167 e:000166 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/runtime.rb:22
c:0015 p:0102 s:0157 e:000156 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0014 p:0016 s:0146 e:000145 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/e
c:0013 p:0102 s:0138 e:000137 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0012 p:0085 s:0127 e:000126 METHOD /app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/s
c:0011 p:0102 s:0119 e:000118 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0010 p:0008 s:0108 e:000107 METHOD /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/sendfile.rb:111
c:0009 p:0102 s:0096 e:000095 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0008 p:0020 s:0085 e:000084 METHOD /app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:524
c:0007 p:0102 s:0079 e:000078 METHOD /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumen
c:0006 p:0026 s:0068 e:000067 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227
c:0005 p:0259 s:0063 e:000062 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660
c:0004 p:0026 s:0038 e:000037 METHOD /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474
c:0003 p:0065 s:0026 e:000025 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334
c:0002 p:0127 s:0016 e:000015 BLOCK  /app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/engine.rb:524:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/static.rb:127:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/lock.rb:17:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/lib/rails/extensions/middleware.rb:235:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/lib/rails/extensions/middleware.rb:198:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/lib/rails/extensions/middleware.rb:14:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/lib/rails/extensions/middleware.rb:173:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/app/lib/rails/extensions/middleware.rb:183:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/lib/rails/extensions/middleware.rb:184:in `block (2 levels) in call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:26:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.5/lib/rails/rack/logger.rb:38:in `call_app'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/lib/rails/extensions/middleware.rb:213:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:98:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:253:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/session/abstract/id.rb:259:in `context'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.5/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/conditional_get.rb:25:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:36:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:75:in `print'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:75:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:88:in `block in print'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:88:in `open'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/rack.rb:89:in `block (2 levels) in print'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:66:in `print'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:90:in `print_threads'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:90:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:91:in `block in print_threads'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:96:in `print_thread'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/printers/abstract_printer.rb:105:in `print_header'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/thread.rb:5:in `total_time'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof/thread.rb:5:in `call_tree'
```

* Puma
* `RAILS_ENV=profile bin/rails s`
* `config.middleware.use(Rack::RubyProf, path: './tmp/profile') if Rails.env.profile?`
* no `profile` line in `newrelic.yml` hence `** [NewRelic] FATAL : Config file at /Users/quinnchaffee/code/finalforms/amp-rails-2/config/newrelic.yml doesn't include a 'profile' section!`

**Comment by wyhaines** [comment]
👀

**Comment by kaylareopelle** [comment]
Hi @chaffeqa, 

Do you happen to have the following two config values set in your `profile` environment? 
```
config.cache_classes = true
config.cache_template_loading = true
```

Those settings are false by default. The [ruby-prof docs](https://ruby-prof.github.io/) section on Profiling Rails asks them to be set to true. When they were false, I had the segfault error with a similar output. When set to true, I was able to profile with the agent without an issue.

**Comment by kaylareopelle** [comment]
I'm going to close this issue for now. Please reopen if the above suggestion doesn't resolve the segfault. Thanks for contributing!
