### ISSUE TITLE
NewRelic Ruby agent failing to start on Ruby 2.7.2, Rails 6.0 with addressable gem

### ISSUE THREAD

**Issue by jeanmw** [newrelic/newrelic-ruby-agent#883]
## Description
Rails 6.0/Ruby 2.7 failing with `addressable` gem (seen on heroku logs)
```
#<Thread:0x000055f0ab990df8 /tmp/build_3dc17b75/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
       /tmp/build_3dc17b75/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `hash': stack level too deep (SystemStackError)
       	from /tmp/build_3dc17b75/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `lookup_unicode_composition'
       	from /tmp/build_3dc17b75/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:185:in `unicode_compose_pair'
       	from /tmp/build_3dc17b75/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
```

addressable/idna/pure.rb for reference:
https://github.com/sporkmonger/addressable/blob/f3fb80c0adb60ce7012c36e5d3714b037a280b06/lib/addressable/idna/pure.rb#L307

## Expected Behavior
The latest version of `newrelic_rpm` should work with the  Rails 6.0/Ruby 2.7 apps

A similar issue is found here: 
https://github.com/sporkmonger/addressable/issues/65

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
full trace:
```
       #<Thread:0x0000562a94ac5f70 /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
       /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `hash': stack level too deep (SystemStackError)
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `lookup_unicode_composition'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:185:in `unicode_compose_pair'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:149:in `unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:121:in `unicode_normalize_kc'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/uri.rb:583:in `normalize_component'
       	 ... 10681 levels...
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:678:in `catch_errors'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:697:in `deferred_work!'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:724:in `block in start_worker_thread'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
       #<Thread:0x0000558b11a53d80 /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
       /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `hash': stack level too deep (SystemStackError)
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `lookup_unicode_composition'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:185:in `unicode_compose_pair'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:149:in `unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:121:in `unicode_normalize_kc'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/uri.rb:583:in `normalize_component'
       	 ... 10681 levels...
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:678:in `catch_errors'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:697:in `deferred_work!'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:724:in `block in start_worker_thread'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
       /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `hash': stack level too deep (SystemStackError)
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `lookup_unicode_composition'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:185:in `unicode_compose_pair'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:149:in `unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:121:in `unicode_normalize_kc'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/uri.rb:583:in `normalize_component'
       	 ... 10681 levels...
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:678:in `catch_errors'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:697:in `deferred_work!'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:724:in `block in start_worker_thread'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
       /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `hash': stack level too deep (SystemStackError)
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:307:in `lookup_unicode_composition'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:185:in `unicode_compose_pair'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.0/lib/active_support/core_ext/range/each.rb:9:in `each'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:149:in `unicode_compose'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/idna/pure.rb:121:in `unicode_normalize_kc'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/addressable-2.8.0/lib/addressable/uri.rb:583:in `normalize_component'
       	 ... 10681 levels...
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:678:in `catch_errors'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:697:in `deferred_work!'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/agent.rb:724:in `block in start_worker_thread'
       	from /tmp/build_49b7c408/vendor/bundle/ruby/2.7.0/gems/newrelic_rpm-8.2.0/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
```

## Steps to Reproduce
Please be as specific as possible.

I believe this is reproducible with a gemfile like so (this is our gemfile):
```
source "https://rubygems.org"

ruby "2.7.2"
gem "active_model_serializers"
gem "active_record_union"
gem "activerecord-import"
gem "audited", "~> 4.3"
gem "hashie"
gem "pg"
gem "puma", "~> 3.11"
gem "rails", "6.0"

gem "device_detector"
gem "jsonapi-serializer"

gem "nokogiri"
gem "nokogumbo", "1.1.9"

gem "handlebars_assets"
gem "uglifier", ">= 1.0.3"

gem "flamegraph"
gem "memory_profiler"
gem "rack-mini-profiler"
gem "stackprof"

# bootstrap/less
gem "mini_racer"
# This needs to be frozen at 3.x in order to be used with ruby 2.5
gem "psych", "~> 3.3.1"

# This specific commit boosts the underlying version of less-rails
# Can remove if/when https://github.com/metaskills/less-rails-bootstrap/pull/132 gets merged
gem "bootstrap-sass", "~> 3.4.1"
gem "sassc-rails", ">= 2.1.0"

# mobile
gem "houston"

## javascripts and views gems
gem "sass"
gem "sprockets"
gem "webpacker"
# Temporarily use fork of simple_form
# https://github.com/plataformatec/simple_form/issues/1485#issuecomment-298607894
gem "american_date"
gem "bootstrap-toggle-rails"
gem "gon"
gem "html_truncator"
gem "jbuilder"
gem "react-rails"
gem "simple_form"
gem "turbolinks", "~> 5.0.0"
gem "will_paginate"
gem "will_paginate-bootstrap"

## authentication & authorization gems
gem "authlogic"
gem "cancancan"
gem "draper-cancancan"
gem "jwt"

## tools gems
gem "ancestry"
gem "chronic"
gem "clearbit"
gem "dalli"
gem "diff-lcs"
gem "draper"
gem "eco"
gem "elasticsearch-model", "~> 5.0.2"
gem "elasticsearch-rails", "~> 5.0.2"
gem "embedly", require: false
gem "font-awesome-rails"
gem "friendly_id"
gem "holidays"
gem "html-pipeline"
gem "htmlentities"
gem "intercom", "~> 3.5.23" # upgrading to new intercom API; old API keys were deprecated
gem "intercom-rails"
gem "koala"
gem "mdl", "~> 0.11.0"
gem "mixpanel-ruby"
gem "newrelic_rpm"
gem "rack-rewrite"
gem "rack-timeout"
gem "rails_autolink"
gem "redcarpet"
gem "rest-client", "2.0.1"
gem "retries"
gem "ruby-progressbar", require: false
gem "ruby-readability", require: "readability"
gem "sanitize"
gem "secure_headers"
gem "sentry-ruby"
gem "spreadsheet"
gem "validate_url"

# logging
gem "lograge"

gem "sidekiq", "~>4.0"
# slim & sinatra for sidekiq monitoring
gem "sinatra", "2.0.0.beta2", require: nil

# salesforce integration
gem "restforce"

## mailer gems
gem "premailer-rails"

## uploading and image processing gems
gem "carrierwave"
gem "fog-aws"
gem "mini_magick"
gem "paperclip"

# Google Auth
gem "omniauth", "1.9.1"
gem "omniauth-google-oauth2", "0.8.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.1.0", require: false

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  gem "bullet"
  gem "launchy"
  gem "listen"
  gem "prettier"
  gem "pry-rails"
  gem "solargraph"
  gem "spring"
end

group :development, :test do
  # Pronto used to send linter results to GitHub
  # May need to `brew install cmake` locally
  gem "byebug"
  gem "dotenv-rails"
  gem "jazz_fingers"
  gem "pronto"
  gem "pronto-rubocop", require: false
  gem "rspec-rails"
  gem "rubocop", "0.82", require: false
  gem "rubocop-performance", "1.5.1", require: false
end

group :development, :test, :staging do
  gem "faker"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "elasticsearch-extensions"
  gem "factory_bot_rails"
  gem "jsonapi-rspec"
  gem "rails-controller-testing"
  gem "rb-fsevent", require: false
  gem "rspec-retry"
  gem "rspec_junit_formatter"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "spring-commands-rspec"
  gem "turn", require: false
  gem "webmock", "3.5.1", require: false

  # Capybara webdrivers
  # Note that because we're using an old version of Ruby, this workaround bust be applied on macOS (also see README):
  # brew install v8@3.15
  # bundle config build.libv8 --with-system-v8
  gem "webdrivers"

  gem "capybara-screenshot"
  gem "climate_control"
  gem "email_spec"
  gem "json_schemer"
  gem "json_spec"
  gem "rack_session_access"
  gem "rb-inotify", "~> 0.9", require: false
  gem "timecop"
  gem "vcr", "~> 2.9.0"
end

group :production, :staging do
  gem "rails_12factor"
end
```

## Your Environment
Rails 6.0, Ruby 2.7.2

## Additional context
I have tried updating these settings:
```
 instrumentation:
    logger: chain
    net_http: chain
    httpclient: chain
    delayed_job: chain
    rake: chain
    sinatra: chain
    puma_rack: chain
    puma_rack_urlmap: chain
    memcached: chain
    memcache_client: chain
    memcache: chain
    httprb: chain
    redis: chain
    rack: chain
    tilt: chain
    excon: chain
    rack_urlmap: chain
```
but had no success.

**Comment by jeanmw** [comment]
I get this even when I roll back `newrelic_rpm` gem to version 6.15.0.

**Comment by jeanmw** [comment]
UPDATE: I have traced the issue back to a sentry-ruby known issue.
Reverting to the old sentry-raven solution works, although nonideal.

https://githubmemory.com/repo/getsentry/sentry-ruby/issues/1427

**Comment by tannalynn** [comment]
hello @jeanmw 
Thanks for letting us know about this issue you're experiencing. That's great you were able to find a workaround by reverting the sentry-raven version, but I do see why that is not ideal.

I tried to reproduce the issue with the same gemfile you provided and I wasn't able to reproduce the issue, but I'm not sure why since a prepend/method chaining conflict typically is pretty easy to reproduce. Also, It's very surprising that trying both 6.15.0 and 7.0.0+ didn't solve the issue with either, since 7.0.0 is when we moved to using Module#prepend by default, and previous to that we were using method chaining. 

Reading the issue you linked, my understanding is that they are using Module#prepend. The new relic agent will use method chaining when a gem that has been previously reported to us to cause conflicts leading to the stack level too deep errors. `Rack::MiniProfiler` is one of the common conflicting gems since the default behavior for that gem is method chaining. However, they do have a prepend patch available. You can force the new relic agent to use prepend no matter what gems are present by setting the configuration option to 'prepend', rather than the default value 'auto' (which checks for those previously reported/ common conflicts).

I do have another idea of a something you may want to try with the newer sentry-ruby version to see if this will prevent the error from happening.
- with the newer sentry-ruby version
- add the following to the newrelic.yml file
```
# newrelic.yml
instrumentation:
  net_http: prepend
```
- install the rack-mini-profiler prepend patch in the gemfile using
```
# Gemfile
gem 'rack-mini-profiler', require: ['prepend_net_http_patch']
```

This should force everything into prepend and hopefully avoid this issue. If not, there may be another location that is also interfering with NetHttp, but we can't see it since the middle of the stack traces are cut out (where it says `... 10681 levels...`). If you are able to get it, seeing the truncated section of the stack traces should help identify where the conflicts are coming from.
But hopefully this suggestion does help avoid the Module#prepend method alias issues.

**Comment by tannalynn** [comment]
> Just wanted to say, I used this workaround as suggested and it fixed the issue but with the following small change:
> 
> `gem 'rack-mini-profiler', require: ['prepend_net_http_patch' , 'rack-mini-profiler']`
> 
> in addition to the upgrade to sentry-ruby and configuration change to net_http in `newrelic.yml`
> 
> Thanks!

@jeanmw I'm glad that you were able to get it working! Thank you for letting us know about what you had to do differently in order to get it working, that will be very helpful for us the next time we run into issues with that gem.
