### ISSUE TITLE
Ruby on rails, [BUG] Segmentation fault at 0x0020ffffa975367c

### ISSUE THREAD

**Issue by almokhtarbr** [newrelic/newrelic-ruby-agent#931]
## Steps to Reproduce
I simply followed all steps to add newrelic to my Ruby application locally
add this to my gemfile  ```gem 'newrelic_rpm'```
i run ```bundle install```
then i added newrelic.yml to config folder 
then i restarted my application 

## Your Environment
macOS monterey 12.1 (apple M1 pro)
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [aarch64-linux]
Rails 7.0.0
docker 4.3.2

## Description
After i start rails server i get this 
```
/usr/local/lib/ruby/2.7.0/openssl/buffering.rb:383: [BUG] Segmentation fault at 0x0020ffffa975367c
       | ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [aarch64-linux]
       |
       | -- Control frame information -----------------------------------------------
       | c:0054 p:---- s:0310 e:000309 CFUNC  :syswrite_nonblock
       | c:0053 p:0011 s:0304 e:000303 METHOD /usr/local/lib/ruby/2.7.0/openssl/buffering.rb:383
       | c:0052 p:0020 s:0297 e:000296 BLOCK  /usr/local/lib/ruby/2.7.0/net/protocol.rb:277 [FINISH]
       | c:0051 p:---- s:0289 e:000288 IFUNC
       | c:0050 p:---- s:0286 e:000285 CFUNC  :each
       | c:0049 p:---- s:0283 e:000282 CFUNC  :each_with_index
       | c:0048 p:0030 s:0279 e:000278 METHOD /usr/local/lib/ruby/2.7.0/net/protocol.rb:275
       | c:0047 p:0008 s:0273 e:000272 BLOCK  /usr/local/lib/ruby/2.7.0/net/protocol.rb:248
       | c:0046 p:0019 s:0270 e:000269 METHOD /usr/local/lib/ruby/2.7.0/net/protocol.rb:265
       | c:0045 p:0004 s:0265 e:000264 METHOD /usr/local/lib/ruby/2.7.0/net/protocol.rb:247
       | c:0044 p:0099 s:0260 e:000259 METHOD /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:335
       | c:0043 p:0027 s:0251 e:000250 METHOD /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:187
       | c:0042 p:0017 s:0243 e:000242 METHOD /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:123
       | c:0041 p:0018 s:0236 e:000235 BLOCK  /usr/local/lib/ruby/2.7.0/net/http.rb:1521 [FINISH]
       | c:0040 p:---- s:0233 e:000232 CFUNC  :catch
       | c:0039 p:0015 s:0228 e:000227 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:1519
       | c:0038 p:0051 s:0220 e:000219 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:1492
       | c:0037 p:0014 s:0212 e:000211 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15
       | c:0036 p:0003 s:0209 e:000208 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26
       | c:0035 p:0009 s:0206 e:000205 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/tracer.rb:351
       | c:0034 p:0023 s:0200 e:000199 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25
       | c:0033 p:0024 s:0197 e:000196 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502
       | c:0032 p:0087 s:0193 e:000192 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24
       | c:0031 p:0006 s:0184 e:000183 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15
       | c:0030 p:0033 s:0177 e:000176 BLOCK  /usr/local/lib/ruby/2.7.0/net/http.rb:1485
       | c:0029 p:0032 s:0174 e:000173 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:933
       | c:0028 p:0012 s:0170 e:000169 METHOD /usr/local/lib/ruby/2.7.0/net/http.rb:1483
       | c:0027 p:0014 s:0162 e:000161 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15
       | c:0026 p:0003 s:0159 e:000158 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26
       | c:0025 p:0009 s:0156 e:000155 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/tracer.rb:351
       | c:0024 p:0023 s:0150 e:000149 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25
       | c:0023 p:0024 s:0147 e:000146 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502
       | c:0022 p:0087 s:0143 e:000142 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24
       | c:0021 p:0006 s:0134 e:000133 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15
       | c:0020 p:0007 s:0127 e:000126 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:539
       | c:0019 p:0033 s:0124 E:000398 BLOCK  /usr/local/lib/ruby/2.7.0/timeout.rb:95
       | c:0018 p:0005 s:0118 e:000117 BLOCK  /usr/local/lib/ruby/2.7.0/timeout.rb:33 [FINISH]
       | c:0017 p:---- s:0115 e:000114 CFUNC  :catch
       | c:0016 p:0044 s:0110 e:000109 METHOD /usr/local/lib/ruby/2.7.0/timeout.rb:33
       | c:0015 p:0112 s:0104 E:0025e0 METHOD /usr/local/lib/ruby/2.7.0/timeout.rb:110
       | c:0014 p:0268 s:0092 E:002548 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:538
       | c:0013 p:0211 s:0079 e:000078 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:440
       | c:0012 p:0111 s:0061 e:000060 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:104
       | c:0011 p:0014 s:0054 e:000053 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:75
       | c:0010 p:0057 s:0045 E:0012e8 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:824
       | c:0009 p:0102 s:0038 E:001330 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:942
       | c:0008 p:0007 s:0030 E:0013c0 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:697
       | c:0007 p:0024 s:0027 E:001420 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502
       | c:0006 p:0017 s:0023 E:001390 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:696
       | c:0005 p:0002 s:0020 E:001488 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:676
       | c:0004 p:0004 s:0015 E:001368 METHOD /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:695
       | c:0003 p:0006 s:0010 E:0014b0 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:722
       | c:0002 p:0006 s:0007 E:0014e8 BLOCK  /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/threading/agent_thread.rb:13 [FINISH]
       | c:0001 p:---- s:0003 e:000002 (none) [FINISH]
       |
       | -- Ruby level backtrace information ----------------------------------------
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/threading/agent_thread.rb:13:in `block in create'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:722:in `block in start_worker_thread'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:695:in `deferred_work!'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:676:in `catch_errors'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:696:in `block in deferred_work!'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502:in `disable_all_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:697:in `block (2 levels) in deferred_work!'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:942:in `connect'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/agent.rb:824:in `connect_to_server'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:75:in `connect'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:104:in `preconnect'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:440:in `invoke_remote'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:538:in `send_request'
       | /usr/local/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
       | /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
       | /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `catch'
       | /usr/local/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
       | /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/new_relic_service.rb:539:in `block in send_request'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `request_with_newrelic_trace'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24:in `request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502:in `disable_all_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25:in `block in request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/tracer.rb:351:in `capture_segment_error'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26:in `block (2 levels) in request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `block in request_with_newrelic_trace'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1483:in `request'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:933:in `start'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `request_with_newrelic_trace'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:24:in `request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent.rb:502:in `disable_all_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:25:in `block in request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/tracer.rb:351:in `capture_segment_error'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/instrumentation.rb:26:in `block (2 levels) in request_with_tracing'
       | /bundle/vendor/ruby/2.7.0/gems/newrelic_rpm-8.4.0/lib/new_relic/agent/instrumentation/net_http/chain.rb:15:in `block in request_with_newrelic_trace'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1492:in `request'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
       | /usr/local/lib/ruby/2.7.0/net/http.rb:1521:in `block in transport_request'
       | /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:123:in `exec'
       | /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:187:in `send_request_with_body'
       | /usr/local/lib/ruby/2.7.0/net/http/generic_request.rb:335:in `write_header'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:247:in `write'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:265:in `writing'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:248:in `block in write'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:275:in `write0'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:275:in `each_with_index'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:275:in `each'
       | /usr/local/lib/ruby/2.7.0/net/protocol.rb:277:in `block in write0'
       | /usr/local/lib/ruby/2.7.0/openssl/buffering.rb:383:in `write_nonblock'
       | /usr/local/lib/ruby/2.7.0/openssl/buffering.rb:383:in `syswrite_nonblock'
       |
       | -- C level backtrace information -------------------------------------------
 exited with code 139
```

**Comment by kaylareopelle** [comment]
Hi @almokhtarbr! Thanks for reaching out. We haven't seen this issue before, however, we've seen complications with Net::HTTP and the `chain` setting with other errors.

Could you try setting the following value in your `newrelic.yml` configuration file?

```yaml
instrumentation.net_http: prepend
```

**Comment by angelatan2** [comment]
Hello @almokhtarbr,  did you get a chance to try the setting suggested by @kaylareopelle ?  We would love to hear if that setting addressed the issue that you encountered. Please drop us a note when you get a chance.

**Comment by angelatan2** [comment]
Closing this issue since there is no further feedback.
